version: '3.8'

services:
  connect-wpp:
    image: reconecta-wpp:latest
    networks:
      - network_swarm_public
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 10s
        order: stop-first
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=network_swarm_public"
        - "traefik.http.routers.connect-wpp.rule=Host(`connect.mlgrupo.com.br`)"
        - "traefik.http.routers.connect-wpp.entrypoints=websecure"
        - "traefik.http.routers.connect-wpp.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.connect-wpp.loadbalancer.server.port=80"
    environment:
      - PORT=80
      - NODE_ENV=production
      - VITE_EVOLUTION_API_KEY=ST73WdmwZr7A6de9RrE7y8MBs6JQchZ8
      - VITE_EVOLUTION_BASE_URL=https://api.supercaso.com.br

networks:
  network_swarm_public:
    external: true
